# SITE CONFIGURATION
title: Surge Synth Team # your site title
author: surgeteam # You :P
description: > # Meta description of Homepage
  We maintain and contribute to awesome open source audio plugins!
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://surge-synth-team.org/' # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://www.facebook.com/groups/surgesynth/
    - https://github.com/surge-synthesizer
    - https://www.kvraudio.com/forum/viewtopic.php?f=1&t=511922

# THEME SETTINGS
navigation: # Navigation links
  - { name: 'Home', link: '/' }
  - { name: 'Open Source', link: '/open-source' }
  - { name: 'Reviews and Guides', link: '/reviews-and-guides' }
  - { name: 'Contact Us', link: '/contact-us' }

tagline: >
  The Surge Synth Team is a group of musicians, developers, testers, documenters, and general
  volunteer open source enthusiasts who randomly assembled to work on the Surge Synthesizer.
  As the Surge project became more successful, and we kept having fun, we decided to branch
  out into other things too!

hero_img: posts/surge_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: no-reply@github.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username: surge-synthesizer # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
# shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
